server:
  port: 8088


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.187.22.37:3308/librarysystem?serverTimezone=Asia/Seoul
    username: root
    password: password!
  jpa:
    hibernate:
      ddl-auto: update #create update none

    show-sql: true
  main:
    allow-circular-references: true
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
